# Timeline Filter Configuration
# This file configures per-user filtered timeline feeds
# Later this will be managed via web interface, but for now it's YAML-based

timeline_feeds:
  # Single test user with all available settings documented
  - did: "did:plc:your-user-did-here"
    feed_uri: "at://did:plc:your-feedgen-did/app.bsky.feed.generator/filtered-timeline"
    name: "My Filtered Timeline"
    description: "Following feed without annoying reposts"

    # OAuth credentials for accessing the user's timeline
    oauth:
      # REQUIRED: Access token from Bluesky OAuth or session
      access_token: "your-access-token-here"

      # OPTIONAL: Refresh token for automatic token renewal
      # refresh_token: "your-refresh-token-here"

      # OPTIONAL: Token expiration timestamp (ISO 8601 format)
      # expires_at: "2025-12-31T23:59:59Z"

      # REQUIRED: Initial PDS URL for token refresh
      # For Bluesky users: Use https://bsky.social (will auto-update to real PDS endpoint)
      # For self-hosted PDS: Use your PDS URL
      pds_url: "https://bsky.social"

    # Filtering configuration
    filters:
      # List of DIDs whose reposts will be filtered out
      # Note: Original posts from these users will still appear, only their reposts are blocked
      blocked_reposters:
        - "did:plc:example-annoying-reposter"
        # Add more DIDs as needed

    # OPTIONAL: How often to poll for BACKFILL (older posts with cursor)
    # Format: "10s", "30s", "1m", "5m", etc.
    # Default: 10s
    # Note: New posts are always polled every 60s (hardcoded, independent of this setting)
    poll_interval: "30s"

    # OPTIONAL: Maximum posts to fetch per poll
    # Range: 1-100, Default: 50
    # Recommended: 100 for faster backfill
    max_posts_per_poll: 100

    # OPTIONAL: Maximum number of posts to index during initial backfill
    # - Default: 500 (recommended for most users, ~2-3 days of history)
    # - Range: 1-5000 (recommended maximum: 5000)
    # - Set to null for unlimited backfill (WARNING: may take hours!)
    #
    # IMPORTANT: Should match CLEANUP_TASK_MAX_AGE!
    # - CLEANUP_TASK_MAX_AGE=48h → backfill_limit: 500-1000 (recommended)
    # - CLEANUP_TASK_MAX_AGE=7d  → backfill_limit: 3500-5000
    # - Posts older than CLEANUP_TASK_MAX_AGE will be deleted anyway!
    # - Higher backfill_limit than cleanup age = wasted startup time
    #
    # How it works:
    # - Backfill fetches older posts using cursor pagination
    # - Stops when this limit is reached OR when cursor becomes undefined (no more posts)
    # - With 500: Fast startup (~2-5 minutes), reasonable history
    # - With null: Complete timeline history but much slower startup
    backfill_limit: 500

# How to get your DID:
# - Go to https://bsky.app/settings
# - Your DID is shown at the bottom (starts with "did:plc:")

# How to get an access token:
# Option 1: App Password (quick but tokens expire)
#   curl -X POST https://bsky.social/xrpc/com.atproto.server.createSession \
#     -H "Content-Type: application/json" \
#     -d '{"identifier": "your-handle.bsky.social", "password": "your-app-password"}'
#   Copy the "accessJwt" value
#
# Option 2: OAuth flow (recommended for production)
#   Implement proper OAuth 2.0 flow - see AT Protocol docs

# Notes:
# - Multiple users can be configured by adding more items to the list
# - Each user needs their own OAuth token
# - DIDs must start with "did:" (e.g., "did:plc:...")
# - Feed URIs must start with "at://"
# - This config will eventually be replaced by web-based configuration
# - Multiple users are polled IN PARALLEL for better performance

# Example: Matching backfill_limit with CLEANUP_TASK_MAX_AGE
#
# IMPORTANT: Configure both together for optimal performance!
#
# Scenario 1: Default (2 days history)
# .env: CLEANUP_TASK_MAX_AGE=48h
# config.yml: backfill_limit: 500-1000
# → Fast startup, small DB, 2 days of posts
#
# Scenario 2: Extended (1 week history)
# .env: CLEANUP_TASK_MAX_AGE=7d
# config.yml: backfill_limit: 3500-5000
# → Moderate startup, medium DB, 1 week of posts
#
# Scenario 3: Archive (1 month history)
# .env: CLEANUP_TASK_MAX_AGE=30d
# config.yml: backfill_limit: null
# → Slow startup, large DB, 1 month of posts
#
# timeline_feeds:
#   # Example: Standard 2-day feed
#   - did: "did:plc:alice"
#     feed_uri: "at://did:plc:feedgen/app.bsky.feed.generator/alice-filtered"
#     name: "Alice's Feed"
#     description: "Filtered timeline (2 days)"
#     oauth:
#       access_token: "alice-token"
#       pds_url: "https://bsky.social"
#     backfill_limit: 1000  # Matches CLEANUP_TASK_MAX_AGE=48h
#     filters:
#       blocked_reposters:
#         - "did:plc:annoying-user"
